set(ENUM_TEMPLATES EXPORT_VAR)

set(TARGET_PARAMETERS 
	IMPLICIT_EXPORTED_DEFAULT	SCALAR	STRING	"default_implicit_exported_default"
)

set(TARGET_FEATURES 
	IMPLICIT_EXPORTED	SCALAR	STRING	"default_implicit_exported"
)

set(TEMPLATE_OPTIONS
	EXPORTED_VARIABLES IMPLICIT_EXPORTED IMPLICIT_EXPORTED_DEFAULT
)

function(apply_dependency_to_target DEPENDEE_TARGET_NAME OUR_TARGET_NAME)

endfunction()
