set(ENUM_TEMPLATES NESTED_EMPTY_LIB)

set(TARGET_PARAMETERS 
)

set(LINK_PARAMETERS 
	NESTED_LIBPAR	SCALAR	INTEGER	23
)

set(TEMPLATE_OPTIONS
#	EXPORTED_VARIABLES LIB_MYVAR
)

function(apply_dependency_to_target DEPENDEE_TARGET_NAME OUR_TARGET_NAME)
	message(STATUS "apply_dependency_to_target for NESTED_EMPTY_LIB: NESTED_LIBPAR: ${NESTED_LIBPAR}")
	target_compile_definitions(${DEPENDEE_TARGET_NAME} ${KEYWORD} "NESTED_LIBPAR=${NESTED_LIBPAR}")
endfunction()
