set(ENUM_TARGETS MPI::MPI_FORTRAN MPI::MPI_CXX)

set(TEMPLATE_OPTIONS
	NICE_NAME "MPI library"
)

set(DEFINE_EXTERNAL_PROJECT 
	ASSUME_INSTALLED
	NAME MPI
	APT_PACKAGES mpi-default-dev
	SPACK_PACKAGES openmpi
)

