#Function stores all entries to the filedb. 
function(_store_file __ARGS __PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED __EXTERNAL_PROJECT_INFO__REF __TARGET_REQUIRED __TEMPLATE_OPTIONS__REF __ALL_TEMPLATE_NAMES __OUT_FILE_HASH)
	_make_path_hash(${__TARGETS_CMAKE_PATH} __PATH_HASH)
	set(${__OUT_FILE_HASH} "${__PATH_HASH}" PARENT_SCOPE)
	_retrieve_file_data(${__PATH_HASH} PATH __TARGETS_CMAKE_PATH_CHECK)
	if(__TARGETS_CMAKE_PATH_CHECK)
		return()
	endif()

	_parse_file_options( "${__TARGETS_CMAKE_PATH}" ${__IS_TARGET_FIXED} ${__TEMPLATE_OPTIONS__REF} __SINGLETON_TARGETS __NO_TARGETS __LANGUAGES __NICE_NAME __EXPORTED_VARS __LINK_TO_DEPENDEE)
	if(__EXPORTED_VARS)
		foreach(__EVAR IN LISTS __EXPORTED_VARS)
			if(NOT "${__EVAR}" IN_LIST ${__PARS}__LIST)
				message(FATAL_ERROR "Cannot export a variable ${__EVAR} that is not defined as a parameter/feature (${__EXPORTED_VARS})")
			endif()
		endforeach()
	endif()
	if(${__EXTERNAL_PROJECT_INFO__REF}__LIST)
		set(__JOINT_TARGETS 1)
		_parse_external_info(${__EXTERNAL_PROJECT_INFO__REF} "${__TARGETS_CMAKE_PATH}" ASSUME_INSTALLED __ASSUME_INSTALLED)
	
		if(NOT __LINK_TO_DEPENDEE)
			_parse_external_info(${__EXTERNAL_PROJECT_INFO__REF} "${__TARGETS_CMAKE_PATH}" LINK_TO_DEPENDEE __LINK_TO_DEPENDEE)
		endif()
		_parse_external_info(${__EXTERNAL_PROJECT_INFO__REF} "${__TARGETS_CMAKE_PATH}" NAME __JOINED_NAME)
	#		message(STATUS "_store_instance_data(): __INSTANCE_ID: ${__INSTANCE_ID} __LINK_TO_DEPENDEE: ${__LINK_TO_DEPENDEE}")
	else()
		set(__ASSUME_INSTALLED 0)
		set(__JOINT_TARGETS 0)
	endif()
	_serialize_parameters(${__PARS} __SERIALIZED_PARAMETERS)

	if(__JOINT_TARGETS)
#		_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_TEMPLATE_NAME       ${__TEMPLATE_NAME})
		_parse_external_info(${__EXTERNAL_PROJECT_INFO__REF} "${__TARGETS_CMAKE_PATH}" NAME __JOINED_NAME)
		if(__JOINED_NAME)
			list(APPEND __ALL_TEMPLATE_NAMES ${__JOINED_NAME})
		endif()
	else()
		set(__JOINED_NAME)
	endif()


	_set_property_to_db(FILEDB     ${__PATH_HASH} PATH                 "${__TARGETS_CMAKE_PATH}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} SINGLETON_TARGETS    "${__SINGLETON_TARGETS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} TARGET_FIXED         "${__IS_TARGET_FIXED}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} NO_TARGETS           "${__NO_TARGETS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_INSTANCES           "")
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_FEATUREBASES        "")
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_TEMPLATES           "")
	_set_property_to_db(FILEDB     ${__PATH_HASH} PARS                 "${__SERIALIZED_PARAMETERS}")
	
	if(__SERIALIZED_PARAMETERS)
		_retrieve_file_data(${__PATH_HASH} DEFAULTS __SERIALIZED_DEFAULTS)
		if(NOT __SERIALIZED_DEFAULTS)
			#We reset all the variables, so we can learn about the defaults
			foreach(__VAR IN LISTS ${__PARS}__LIST)
				set(${__VAR})
			endforeach()
			_get_variables("${__TARGETS_CMAKE_PATH}" "defaults" "" 0 __DEFAULTS __TMP_PARS __TMP_TEMPLATE_NAMES __TMP_EXTERNAL_PROJECT_INFO __TMP_IS_TARGET_FIXED __TMP_GLOBAL_OPTIONS)
			_serialize_variables(__DEFAULTS "${__DEFAULTS__LIST}" __SERIALIZED_DEFAULTS)
#			message(STATUS "_store_instance_data(): __SERIALIZED_DEFAULTS: ${__SERIALIZED_DEFAULTS}")
		endif()
		_set_property_to_db(FILEDB     ${__PATH_HASH} DEFAULTS         "${__SERIALIZED_DEFAULTS}")
	endif()
	_set_property_to_db(FILEDB     ${__PATH_HASH} EXTERNAL_INFO        "${${__EXTERNAL_PROJECT_INFO__REF}__LIST}")
	if(__JOINED_NAME)
		_set_property_to_db(FILEDB     ${__PATH_HASH} JOINED_NAME      "${__JOINED_NAME}")
	endif()
	_set_property_to_db(FILEDB     ${__PATH_HASH} TARGETS_REQUIRED      ${__TARGET_REQUIRED})
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_TEMPLATES          "${__ALL_TEMPLATE_NAMES}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} LANGUAGES            "${__LANGUAGES}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} ASSUME_INSTALLED     "${__ASSUME_INSTALLED}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} NICE_NAME            "${__NICE_NAME}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} EXPORTED_VARS        "${__EXPORTED_VARS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} JOINT_TARGETS        "${__JOINT_TARGETS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} LINK_TO_DEPENDEE     "${__LINK_TO_DEPENDEE}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} TEMPLATE_OPTIONS     "${__TEMPLATE_OPTIONS}")
	
endfunction()

#Each featurebase is a distinctly built set of targets (it may be more than one if the targets are joined as is often the case with external targets). 
#It may not know its all arguments, because part of them are features, that are known only after
#consolidating all instances of this featurebases and the relevant promises.
#
#Function sets the featurebase (and returns its ID). It does not make any connection between the featurebase and the instance
#
#TEMPLATE_NAME is needed for the ability to automatically naming the actual targets.
function(_store_featurebase __ARGS __PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __JOINT_TARGETS __OUT_FEATUREBASE_ID)

	_serialize_variables(${__ARGS} "${${__PARS}__LIST_MODIFIERS}" __SERIALIZED_MODIFIERS)
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_FEATURES}" __SERIALIZED_FEATURES)
	
	_make_featurebase_hash_2("${__SERIALIZED_MODIFIERS}" "${__SERIALIZED_FEATURES}" ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__JOINT_TARGETS} __FEATUREBASE_ID __FEATUREBASE_HASH_SOURCE)
	set(${__OUT_FEATUREBASE_ID} "${__FEATUREBASE_ID}" PARENT_SCOPE)

	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_FEATURES           "${__SERIALIZED_FEATURES}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} MODIFIERS            "${__SERIALIZED_MODIFIERS}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_PATH               "${__TARGETS_CMAKE_PATH}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} TARGET_BUILT          0)
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_HASH_SOURCE         "${__FEATUREBASE_HASH_SOURCE}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} COMPAT_INSTANCES      "")

	_add_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} TEMPLATE_FEATUREBASES        ${__FEATUREBASE_ID})
	_set_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} T_PATH                       ${__TARGETS_CMAKE_PATH})

#	message(STATUS "_store_featurebase(): Adding ${__FEATUREBASE_ID} to all featurebases")
	_add_property_to_db(GLOBAL ALL FEATUREBASES ${__FEATUREBASE_ID})
endfunction()

function(_link_file_with_featurebase __FEATUREBASE_ID __FILE_HASH)
	_add_property_to_db(FILEDB ${__FILE_HASH} G_FEATUREBASES        "${__FEATUREBASE_ID}")
endfunction()

function(_link_instance_with_featurebase __INSTANCE_ID __FEATUREBASE_ID)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} FEATUREBASE "${__FEATUREBASE_ID}")
	_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_INSTANCES "${__INSTANCE_ID}")
endfunction()

#Stores instance data, irrelevant whether it is a promise or not. 
function(_store_instance_data __INSTANCE_ID __ARGS __PARS __TEMPLATE_NAME __IS_TARGET_FIXED __IS_PROMISE )
	if("${__IS_PROMISE}" STREQUAL "")
		message(FATAL_ERROR "__IS_PROMISE cannot be empty")
	endif()
	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __IS_PROMISE_BEFORE)
	if(NOT "${__IS_PROMISE_BEFORE}" STREQUAL "")
#		message(STATUS "_store_instance_data(): __INSTANCE_ID: ${__INSTANCE_ID} already defined. Exiting")
		return()
	endif()
#	message(STATUS "_store_instance_data(): Defining __INSTANCE_ID: ${__INSTANCE_ID}")
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_FEATURES}" __SERIALIZED_FEATURES)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_FEATURES            "${__SERIALIZED_FEATURES}")
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_LINKPARS}" __SERIALIZED_LINKPARS)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} LINKPARS              "${__SERIALIZED_LINKPARS}")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} IS_PROMISE             ${__IS_PROMISE} FORCE)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_TEMPLATE_NAME        ${__TEMPLATE_NAME})
	if(__IS_TARGET_FIXED)
#		message(STATUS "_store_instance_data(): Storing fixed target name for ${__INSTANCE_ID}: ${__TEMPLATE_NAME}")
		_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} TARGET_NAME  ${__TEMPLATE_NAME})
	endif()
	_set_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} T_PATH               ${__TARGETS_CMAKE_PATH})
	
	
endfunction()

#Makes sure a given instance is stored in the memory as a promise. It does not link the instance with the parent - for that use _link_instances_together()
function(_store_virtual_instance_data __INSTANCE_ID __IN_ARGS __IN_PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED  __EXTERNAL_PROJECT_INFO__REF __TARGET_REQUIRED  __TEMPLATE_OPTIONS__REF __ALL_TEMPLATE_NAMES __OUT_FILE_HASH)
#	message(STATUS "_store_virtual_instance_data(): __ALL_TEMPLATE_NAMES: ${__ALL_TEMPLATE_NAMES} __TEMPLATE_NAME: ${__TEMPLATE_NAME}")
	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __IS_PROMISE_BEFORE)
	if("${__IS_PROMISE_BEFORE}" STREQUAL "1" OR "${__IS_PROMISE_BEFORE}" STREQUAL "0")
		#Nothing to do - either the promise is already set or we are not going to overwrite promise on top of actual instance
		return()
	endif()
	_store_file(${__IN_ARGS} ${__IN_PARS} ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__IS_TARGET_FIXED} ${__EXTERNAL_PROJECT_INFO__REF} ${__TARGET_REQUIRED} ${__TEMPLATE_OPTIONS__REF} "${__ALL_TEMPLATE_NAMES}" __FILE_HASH)
	set(${__OUT_FILE_HASH} "${__FILE_HASH}" PARENT_SCOPE)
	
	_store_instance_data(${__INSTANCE_ID} ${__IN_ARGS} ${__IN_PARS} ${__TEMPLATE_NAME} ${__IS_TARGET_FIXED} 1 )
	
#	message(STATUS "_store_virtual_instance_data(): __IS_PROMISE_BEFORE: ${__IS_PROMISE_BEFORE} __ALL_TEMPLATE_NAMES: ${__ALL_TEMPLATE_NAMES} ")
	if(NOT "${__IS_PROMISE_BEFORE}" STREQUAL "1")
		foreach(__TEMPLATE IN LISTS __ALL_TEMPLATE_NAMES)
#			message(STATUS "_store_virtual_instance_data(): adding ${__INSTANCE_ID} to virtual instances of ${__TEMPLATE}")
			_add_property_to_db(TEMPLATEDB ${__TEMPLATE} VIRTUAL_INSTANCES ${__INSTANCE_ID})
		endforeach()
	endif()
	
	
	_debug_show_instance(${__INSTANCE_ID} 2 "" __MSG __ERRORS)
	message(STATUS "_store_virtual_instance_data(): ${__MSG}")
	if(__ERRORS)
		message(FATAL_ERROR ${__ERRORS})
	endif()

endfunction()

function(_unvirtualize_instance __INSTANCE_ID __FEATUREBASE_ID)
	message(STATUS "_unvirtualize_instance(): __INSTANCE_ID: ${__INSTANCE_ID} __FEATUREBASE_ID: ${__FEATUREBASE_ID}")
	_retrieve_instance_data(${__INSTANCE_ID} I_TEMPLATE_NAME __TEMPLATE_NAME)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} IS_PROMISE 0 FORCE)
	_remove_property_from_db(TEMPLATEDB ${__TEMPLATE_NAME} VIRTUAL_INSTANCES ${__INSTANCE_ID})
	_link_instance_with_featurebase(${__INSTANCE_ID} ${__FEATUREBASE_ID})
	
	_retrieve_featurebase_data(${__FEATUREBASE_ID} G_TEMPLATES __ALL_TEMPLATE_NAMES)

	foreach(__TEMPLATE IN LISTS __ALL_TEMPLATE_NAMES)
		message(STATUS "_unvirtualize_instance(): Removing __INSTANCE_ID ${__INSTANCE_ID} from VIRTUAL_INSTANCES of ${__TEMPLATE}")
		_remove_property_from_db(TEMPLATEDB ${__TEMPLATE} VIRTUAL_INSTANCES ${__INSTANCE_ID} FORCE)
	endforeach()
#	message(STATUS "_unvirtualize_instance(): Adding ${__FEATUREBASE_ID} to TEMPLATE_FEATUREBASES for ${__TEMPLATE_NAME}")
endfunction()	

#Makes sure a given instance is stored in the memory as a promise. It does not link the instance with the parent - for that use _link_instances_together()
function(_store_nonvirtual_instance_data __INSTANCE_ID __IN_ARGS __IN_PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED  __EXTERNAL_PROJECT_INFO__REF __TARGET_REQUIRED  __TEMPLATE_OPTIONS__REF __ALL_TEMPLATE_NAMES __OUT_FILE_HASH __OUT_FEATUREBASE_ID)
	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __IS_PROMISE_BEFORE)
	_store_file(${__IN_ARGS} ${__IN_PARS} ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__IS_TARGET_FIXED} ${__EXTERNAL_PROJECT_INFO__REF} ${__TARGET_REQUIRED} ${__TEMPLATE_OPTIONS__REF} "${__ALL_TEMPLATE_NAMES}" __FILE_HASH)
	set(${__OUT_FILE_HASH} "${__FILE_HASH}" PARENT_SCOPE)
	
	if(${__EXTERNAL_PROJECT_INFO__REF}__LIST)
		set(__JOINT_TARGETS 1)
	else()
		set(__JOINT_TARGETS 0)
	endif()
	
	_store_featurebase(${__IN_ARGS} ${__IN_PARS} ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__JOINT_TARGETS} __FEATUREBASE_ID)
	_link_file_with_featurebase(${__FEATUREBASE_ID} ${__FILE_HASH})
	_store_instance_data(${__INSTANCE_ID} ${__IN_ARGS} ${__IN_PARS} ${__TEMPLATE_NAME} ${__IS_TARGET_FIXED} 0 )
	set(${__OUT_FEATUREBASE_ID} ${__FEATUREBASE_ID} PARENT_SCOPE)
	if("${__IS_PROMISE_BEFORE}" STREQUAL "1")
		_unvirtualize_instance(${__INSTANCE_ID} ${__FEATUREBASE_ID})
	else()
		_link_instance_with_featurebase(${__INSTANCE_ID} ${__FEATUREBASE_ID})
	endif()
	
	_debug_show_instance(${__INSTANCE_ID} 2 "" __MSG __ERRORS)
	message(STATUS "_store_nonvirtual_instance_data(): ${__MSG}")
	if(__ERRORS)
		message(FATAL_ERROR ${__ERRORS})
	endif()
endfunction()


#Links two instances together.
#The link from dependee to the dependency is possible only through the featurebase id, so it will not be possible
#(and will trigger the error) if dependee is a promise.
#
#
#If dependee_id is empty, it will be assumed that this instance is top (required by the CMakeLists.txt directly)
#Dependent cannot be empty
#
#DEPENDEE_ID can be empty or non-promise.
#DEPENDENT_ID cannot be empty
function(_link_instances_together __DEPENDEE_ID __DEPENDENT_ID)
	if("${__DEPENDENT_ID}" STREQUAL "")
		message(FATAL_ERROR "Internal beetroot error: __DEPENDENT_ID cannot be empty")
	endif()
	_retrieve_instance_data(${__DEPENDENT_ID} IS_PROMISE __IS_PROMISE)
	if("${__IS_PROMISE}" STREQUAL "")
		message(FATAL_ERROR "Internal beetroot error: __DEPENDENT_ID: ${__DEPENDENT_ID} must be first initialized")
	endif()
#	message(STATUS "_link_instances_together(): __DEPENDEE_ID: ${__DEPENDEE_ID} __DEPENDENT_ID: ${__DEPENDENT_ID}")
	
	_add_property_to_db(INSTANCEDB ${__DEPENDENT_ID} I_PARENTS "${__DEPENDEE_ID}")
	if(__DEPENDEE_ID)
		_retrieve_instance_data(${__DEPENDEE_ID} IS_PROMISE __IS_PROMISE)
		if("${__IS_PROMISE}" STREQUAL "")
			message(FATAL_ERROR "Internal beetroot error: __DEPENDEE_ID: ${__DEPENDEE_ID} must be first initialized")
		endif()
		if(__IS_PROMISE)
			message(FATAL_ERROR "Internal beetroot error: __DEPENDEE_ID: ${__DEPENDEE_ID} cannot be a promise")
		endif()
		_retrieve_instance_data(${__DEPENDEE_ID} FEATUREBASE __DEPENDEE_FEATUREBASE)
		if("${__DEPENDEE_FEATUREBASE}" STREQUAL "")
			message(FATAL_ERROR "Internal beetroot error")
		endif()
		_add_property_to_db(FEATUREBASEDB ${__DEPENDEE_FEATUREBASE} DEP_INSTANCES ${__DEPENDENT_ID})
	else()
		_add_property_to_db(GLOBAL ALL INSTANCES ${__DEPENDENT_ID})
	endif()
endfunction()

#Moves all parents of the __OLD_INSTANCE_ID to the __NEW_INSTANCE_ID,
#unregisters the dependencies of the __OLD_INSTANCE_ID from it and makes sure __OLD_INSTANCE_ID will not be built.
#
#We assume the __NEW_INSTANCE_ID has correct dependencies, but is not dependent on anything.
#
#__OLD_INSTANCE_ID can be a promise (and have no dependencies)
function(_move_instance __OLD_INSTANCE_ID __NEW_INSTANCE_ID )
#	message(FATAL_ERROR "OK")
	#1. For each parent, change its dependency and parent
	_retrieve_instance_data(${__OLD_INSTANCE_ID} I_PARENTS __PARENTS)
	foreach(__PARENT_ID IN LISTS __PARENTS)
		_retrieve_instance_data(${__PARENT_ID} FEATUREBASE __PARENT_FEATUREBASE)
		if(NOT __PARENT_FEATUREBASE)
			message(FATAL_ERROR "Internal beetroot consistency error: Parent does contain a link to the featurebase.")
		endif()
		_remove_property_from_db(FEATUREBASEDB ${__PARENT_FEATUREBASE} DEP_INSTANCES ${__OLD_INSTANCE_ID})
		_add_property_to_db(FEATUREBASEDB ${__PARENT_FEATUREBASE} DEP_INSTANCES ${__NEW_INSTANCE_ID})
		_add_property_to_db(INSTANCEDB ${__NEW_INSTANCE_ID} I_PARENTS ${__PARENT_ID})
		_remove_property_from_db(INSTANCEDB ${__OLD_INSTANCE_ID} I_PARENTS ${__PARENT_ID})
	endforeach()
	
	#2. Change TEMPLATEDB
	_retrieve_instance_data(${__OLD_INSTANCE_ID} VIRTUAL_INSTANCES __PROMISES)
	_retrieve_instance_data(${__OLD_INSTANCE_ID} I_TEMPLATE_NAME __TEMPLATE_NAME)
	_retrieve_instance_data(${__OLD_INSTANCE_ID} IS_PROMISE __IS_PROMISE)
	_retrieve_instance_data(${__NEW_INSTANCE_ID} IS_PROMISE __NEW_IS_PROMISE)
	if("${__IS_PROMISE}" STREQUAL "1")
		message(FATAL_ERROR "Internal beetroot error: There should be no need to move a promise")
	endif()
	if(NOT "${__IS_PROMISE}" STREQUAL "${__NEW_IS_PROMISE}")
		message(FATAL_ERROR "Internal beetroot error: __OLD_INSTANCE_ID: ${__OLD_INSTANCE_ID} __IS_PROMISE: ${__IS_PROMISE} __NEW_INSTANCE_ID: ${__NEW_INSTANCE_ID} __NEW_IS_PROMISE: ${__NEW_IS_PROMISE}")
	endif()
	
	#3. Move instance in 
	_retrieve_instance_data(${__NEW_INSTANCE_ID} FEATUREBASE __NEW_FEATUREBASE)
	_retrieve_instance_data(${__OLD_INSTANCE_ID} IS_PROMISE __IS_PROMISE)
	if("${__IS_PROMISE}" STREQUAL "0")
		_retrieve_instance_data(${__OLD_INSTANCE_ID} FEATUREBASE __OLD_FEATUREBASE)
	else()
		set(__OLD_FEATUREBASE)
	endif()
	if(NOT "${__OLD_FEATUREBASE}" STREQUAL "${__NEW_FEATUREBASE}")
		if(NOT "${__OLD_FEATUREBASE}" STREQUAL "")
			_remove_property_from_db(FEATUREBASEDB ${__OLD_FEATUREBASE} F_INSTANCES ${__OLD_INSTANCE_ID})
		endif()
#		message(STATUS "_move_instance(): Adding instance ${__NEW_INSTANCE_ID} to F_INSTANCES of featurebase ${__NEW_FEATUREBASE}")
		_add_property_to_db(FEATUREBASEDB ${__NEW_FEATUREBASE} F_INSTANCES ${__NEW_INSTANCE_ID})
	endif()
	
	#4. Change __GLOBAL_ALL_INSTANCES
	_retrieve_global_data(INSTANCES __ALL_INSTANCES)
	if(${__OLD_INSTANCE_ID} IN_LIST __ALL_INSTANCES)
		_remove_property_from_db(GLOBAL ALL INSTANCES ${__OLD_INSTANCE_ID})
		_add_property_to_db(GLOBAL ALL INSTANCES ${__NEW_INSTANCE_ID})
	endif()
endfunction()

#Adds an instance to the system
function(_commit_instance_data __INSTANCE_ID __PARENT_INSTANCE_ID __ARGS __PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED __EXTERNAL_PROJECT_INFO__REF __TARGET_REQUIRED __TEMPLATE_OPTIONS__REF __ALL_TEMPLATE_NAMES)

	_store_nonvirtual_instance_data(${__INSTANCE_ID} ${__ARGS} ${__PARS} ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__IS_TARGET_FIXED}  "${__EXTERNAL_PROJECT_INFO__REF}" ${__TARGET_REQUIRED} ${__TEMPLATE_OPTIONS__REF} "${__ALL_TEMPLATE_NAMES}" __FILE_HASH __FEATUREBASE_ID)

	_link_instances_together("${__PARENT_INSTANCE_ID}" ${__INSTANCE_ID})
endfunction()

function(_store_instance_dependencies __INSTANCE_ID __DEP_LIST)
	_retrieve_instance_data(${__INSTANCE_ID} FEATUREBASE __FEATUREBASE_ID)
#	message(STATUS "_store_instance_dependencies(): __INSTANCE_ID: ${__INSTANCE_ID} __DEP_LIST: ${__DEP_LIST} __FEATUREBASE_ID: ${__FEATUREBASE_ID}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} DEP_INSTANCES        "${__DEP_LIST}" $ARGV2)
endfunction()














function(_store_instance_data_OLD __INSTANCE_ID __PARENT_INSTANCE_ID __ARGS __PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED __EXTERNAL_PROJECT_INFO_LIST __TARGET_REQUIRED __TEMPLATE_OPTIONS __ALL_TEMPLATE_NAMES)
	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __IS_PROMISE)
	if(__IS_PROMISE)
		_debug_show_instance(${__INSTANCE_ID} 2 "   " __STR __ERROR)
		if(__ERROR)
			message(FATAL_ERROR "${ERROR}")
		endif()
#		message(STATUS "_store_instance_data():\n ${__STR}")
		message(FATAL_ERROR "applying _store_instance_data to already existing promise")
		_remove_property_from_db(TEMPLATEDB ${__TEMPLATE_NAME} VIRTUAL_INSTANCES ${__INSTANCE_ID})
	endif()

	_parse_file_options(${__INSTANCE_ID} "${__TARGETS_CMAKE_PATH}" ${__IS_TARGET_FIXED} "${__TEMPLATE_OPTIONS}" __SINGLETON_TARGETS __NO_TARGETS __LANGUAGES __NICE_NAME __EXPORTED_VARS __LINK_TO_DEPENDEE)
	if(__EXPORTED_VARS)
		foreach(__EVAR IN LISTS __EXPORTED_VARS)
			if(NOT "${__EVAR}" IN_LIST ${__PARS}__LIST)
				message(FATAL_ERROR "Cannot export a variable ${__EVAR} that is not defined as a parameter/feature (${__EXPORTED_VARS})")
			endif()
		endforeach()
	endif()
	if(${__EXTERNAL_PROJECT_INFO_LIST})
		set(__JOINT_TARGETS 1)
	else()
		set(__JOINT_TARGETS 0)
	endif()
#	message(STATUS "_store_instance_data(): __LANGUAGES: ${__LANGUAGES}")
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_FEATURES}" __SERIALIZED_FEATURES)
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_MODIFIERS}" __SERIALIZED_MODIFIERS)
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_LINKPARS}" __SERIALIZED_LINKPARS)
#	message(STATUS "_store_instance_data(): __SERIALIZED_FEATURES: ${__SERIALIZED_FEATURES}")
#	message(STATUS "_store_instance_data(): __SERIALIZED_MODIFIERS: ${__SERIALIZED_MODIFIERS}")
#	message(STATUS "_store_instance_data(): __SERIALIZED_LINKPARS: ${__SERIALIZED_LINKPARS}")
	_serialize_parameters(${__PARS} __SERIALIZED_PARAMETERS)
	_make_featurebase_hash_2("${__SERIALIZED_MODIFIERS}" "${__SERIALIZED_FEATURES}" ${__TEMPLATE_NAME} "${__TARGETS_CMAKE_PATH}" ${__JOINT_TARGETS} __FEATUREBASE_ID __FEATUREBASE_HASH_SOURCE)
#	message(STATUS "_store_instance_data(): __INSTANCE_ID ${__INSTANCE_ID} got __FEATUREBASE_ID: ${__FEATUREBASE_ID}")
	_make_path_hash(${__TARGETS_CMAKE_PATH} __PATH_HASH)

#	message(FATAL_ERROR "__ARGS_LIST_MODIFIERS: ${__ARGS_LIST_MODIFIERS}")
#	if("${__INSTANCE_ID}" STREQUAL "SerialboxStatic_18768807d4b4034c1c5d4dd0f5ba6964")
#	message(STATUS "_store_instance_data(): __EXTERNAL_PROJECT_INFO_LIST: ${__EXTERNAL_PROJECT_INFO_LIST}: ${${__EXTERNAL_PROJECT_INFO_LIST}}")
 #	endif()
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_FEATURES            "${__SERIALIZED_FEATURES}")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} LINKPARS              "${__SERIALIZED_LINKPARS}")
	if(__PARENT_INSTANCE_ID)
		_add_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_PARENTS              ${__PARENT_INSTANCE_ID})
	endif()
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} IS_PROMISE            "0")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} FEATUREBASE            ${__FEATUREBASE_ID})
	_retrieve_instance_data(${__INSTANCE_ID} FEATUREBASE __TMP)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_TEMPLATE_NAME        ${__TEMPLATE_NAME})
	if(__IS_TARGET_FIXED)
#		message(STATUS "_store_instance_data(): Storing fixed target name for ${__INSTANCE_ID}: ${__TEMPLATE_NAME}")
		_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} TARGET_NAME  ${__TEMPLATE_NAME})
	endif()
	
#	message(STATUS "_store_instance_data(): __INSTANCE_ID: ${__INSTANCE_ID} __FEATUREBASE_ID: ${__FEATUREBASE_ID} __PATH_HASH: ${__PATH_HASH}")
	unset(__FOUND_TMP)
	_retrieve_instance_data(${__INSTANCE_ID} F_INSTANCES __FOUND_TMP)
	if(NOT "${__FOUND_TMP}" STREQUAL "")
#		message(STATUS "_store_instance_data(): Featurebase ${__FEATUREBASE_ID} already defined for instances ${__FOUND_TMP}. Adding another instance: ${__INSTANCE_ID} ")
	else()
		_add_property_to_db(GLOBAL ALL FEATUREBASES ${__FEATUREBASE_ID})
	endif()
	_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_INSTANCES           ${__INSTANCE_ID})
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_FEATURES           "${__SERIALIZED_FEATURES}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} MODIFIERS            "${__SERIALIZED_MODIFIERS}")
	if(__JOINT_TARGETS)
#		_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_TEMPLATE_NAME       ${__TEMPLATE_NAME})
		_parse_external_info(${__EXTERNAL_PROJECT_INFO_LIST} "${__TARGETS_CMAKE_PATH}" NAME __JOINED_NAME)
		if(__JOINED_NAME)
			list(APPEND __ALL_TEMPLATE_NAMES ${__JOINED_NAME})
		endif()
		foreach(__ONE_TEMPLATE_NAME IN LISTS __ALL_TEMPLATE_NAMES)
#			message(STATUS "_store_instance_link_data(): Adding template name: ${__ONE_TEMPLATE_NAME} for FEATUREBASEDB ${__FEATUREBASE_ID}")
			_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_TEMPLATE_NAME            ${__ONE_TEMPLATE_NAME})
		endforeach()
	else()
		_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_TEMPLATE_NAME       ${__TEMPLATE_NAME})
	endif()
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_PATH               "${__TARGETS_CMAKE_PATH}")
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} TARGET_BUILT          0)
	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_HASH_SOURCE         "${__FEATUREBASE_HASH_SOURCE}")

	_add_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} TEMPLATE_FEATUREBASES        ${__FEATUREBASE_ID})
	_set_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} T_PATH                       ${__TARGETS_CMAKE_PATH})


	set(__LINK_TO_DEPENDEE)
	if(${__EXTERNAL_PROJECT_INFO_LIST})
		_parse_external_info(${__EXTERNAL_PROJECT_INFO_LIST} "${__TARGETS_CMAKE_PATH}" ASSUME_INSTALLED __ASSUME_INSTALLED)
		
		if(NOT __LINK_TO_DEPENDEE)
			_parse_external_info(${__EXTERNAL_PROJECT_INFO_LIST} "${__TARGETS_CMAKE_PATH}" LINK_TO_DEPENDEE __LINK_TO_DEPENDEE)
		endif()
		_parse_external_info(${__EXTERNAL_PROJECT_INFO_LIST} "${__TARGETS_CMAKE_PATH}" NAME __JOINED_NAME)
#		message(STATUS "_store_instance_data(): __INSTANCE_ID: ${__INSTANCE_ID} __LINK_TO_DEPENDEE: ${__LINK_TO_DEPENDEE}")
	else()
		set(__ASSUME_INSTALLED)
	endif()
	_set_property_to_db(FILEDB     ${__PATH_HASH} PATH                 "${__TARGETS_CMAKE_PATH}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} SINGLETON_TARGETS    "${__SINGLETON_TARGETS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} TARGET_FIXED         "${__IS_TARGET_FIXED}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} NO_TARGETS           "${__NO_TARGETS}")
	_add_property_to_db(FILEDB     ${__PATH_HASH} G_INSTANCES           ${__INSTANCE_ID})
	_add_property_to_db(FILEDB     ${__PATH_HASH} G_FEATUREBASES        ${__FEATUREBASE_ID})
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_TEMPLATES          "${__ALL_TEMPLATE_NAMES}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} PARS                 "${__SERIALIZED_PARAMETERS}")
	
	if(__SERIALIZED_PARAMETERS)
		_retrieve_instance_data(${__INSTANCE_ID} DEFAULTS __SERIALIZED_DEFAULTS)
		if(NOT __SERIALIZED_DEFAULTS)
			#We reset all the variables, so we can learn about the defaults
			foreach(__VAR IN LISTS ${__PARS}__LIST)
				set(${__VAR})
			endforeach()
			_get_variables("${__TARGETS_CMAKE_PATH}" "defaults" "" 0 __DEFAULTS __TMP_PARS __TMP_TEMPLATE_NAMES __TMP_EXTERNAL_PROJECT_INFO __TMP_IS_TARGET_FIXED __TMP_GLOBAL_OPTIONS)
			_serialize_variables(__DEFAULTS "${__DEFAULTS__LIST}" __SERIALIZED_DEFAULTS)
#			message(STATUS "_store_instance_data(): __SERIALIZED_DEFAULTS: ${__SERIALIZED_DEFAULTS}")
		endif()
		_set_property_to_db(FILEDB     ${__PATH_HASH} DEFAULTS         "${__SERIALIZED_DEFAULTS}")
	endif()
	_set_property_to_db(FILEDB     ${__PATH_HASH} EXTERNAL_INFO        "${__EXTERNAL_PROJECT_INFO}")
	if(__JOINED_NAME)
		_set_property_to_db(FILEDB     ${__PATH_HASH} JOINED_NAME      "${__JOINED_NAME}")
	endif()
	_set_property_to_db(FILEDB     ${__PATH_HASH} TARGETS_REQUIRED      ${__TARGET_REQUIRED})
	_set_property_to_db(FILEDB     ${__PATH_HASH} LANGUAGES            "${__LANGUAGES}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} ASSUME_INSTALLED     "${__ASSUME_INSTALLED}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} NICE_NAME            "${__NICE_NAME}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} EXPORTED_VARS        "${__EXPORTED_VARS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} JOINT_TARGETS        "${__JOINT_TARGETS}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} LINK_TO_DEPENDEE     "${__LINK_TO_DEPENDEE}")
	_set_property_to_db(FILEDB     ${__PATH_HASH} TEMPLATE_OPTIONS     "${__TEMPLATE_OPTIONS}")
	
	if(__JOINT_TARGETS AND "${__TEMPLATE_NAME}" STREQUAL "${__JOINED_NAME}")
#		message(STATUS "_store_instance_data(): JOINT_TARGETS of __INSTANCE_ID: ${__INSTANCE_ID} __FEATUREBASE_ID: ${__FEATUREBASE_ID} __TEMPLATE_NAME: ${__TEMPLATE_NAME}")
		
		_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_TEMPLATE_NAME       ${__TEMPLATE_NAME})
	endif()

	_get_stack_depth(__STACK_DEPTH)
	if("${__STACK_DEPTH}" STREQUAL "0")
#		message(STATUS "_store_instance_data(): ADDING GLOBAL INSTANCE: ${__INSTANCE_ID}")
		_add_property_to_db(GLOBAL ALL INSTANCES "${__INSTANCE_ID}")
	endif()
	
#	_append_instance_modifiers_hash(${__INSTANCE_ID} ${__TEMPLATE_NAME} ${__ARGS} "${__ARGS_LIST_MODIFIERS}")
endfunction()

#Stores just enough information to store template id, features and target parameters (modifiers). Essentially enough to set a link to the existing FILEDB and FEATUREBASEDB.
#It excludes dependencies. 
function(_store_instance_link_data_OLD __INSTANCE_ID __PARENT_INSTANCE_ID __ARGS __PARS __TEMPLATE_NAME __TARGETS_CMAKE_PATH __IS_TARGET_FIXED __ALL_TEMPLATE_NAMES)
	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __IS_PROMISE)
	if("${__IS_PROMISE}" STREQUAL "0")
		_debug_show_instance(${__INSTANCE_ID} 2 "   " __STR __ERROR)
		if(__ERROR)
			message(FATAL_ERROR "${__ERROR}")
		endif()
		message(STATUS "_store_instance_link_data():\n ${__STR}")
		message(FATAL_ERROR "applying _store_instance_link_data to already exsting instance, not promise")
	endif()

	_serialize_variables(${__ARGS} "${${__PARS}__LIST_FEATURES}" __SERIALIZED_FEATURES)
	_serialize_variables(${__ARGS} "${${__PARS}__LIST_LINKPARS}" __SERIALIZED_LINKPARS)
#	message(STATUS "_store_instance_link_data(): __SERIALIZED_FEATURES: ${__SERIALIZED_FEATURES}")
#	message(STATUS "_store_instance_link_data(): __SERIALIZED_MODIFIERS: ${__SERIALIZED_MODIFIERS}")
#	message(STATUS "_store_instance_link_data(): __SERIALIZED_LINKPARS: ${__SERIALIZED_LINKPARS}")
	_serialize_parameters(${__PARS} __SERIALIZED_PARAMETERS)
	if(${__EXTERNAL_PROJECT_INFO_LIST})
		set(__JOINT_TARGETS 1)
	else()
		set(__JOINT_TARGETS 0)
	endif()

	_make_path_hash(${__TARGETS_CMAKE_PATH} __PATH_HASH)

#	message(FATAL_ERROR "__ARGS_LIST_MODIFIERS: ${__ARGS_LIST_MODIFIERS}")
#	if("${__INSTANCE_ID}" STREQUAL "SerialboxStatic_18768807d4b4034c1c5d4dd0f5ba6964")
#		message(FATAL_ERROR "__EXTERNAL_PROJECT_INFO_LIST: ${__EXTERNAL_PROJECT_INFO_LIST}")
 #	endif()
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_FEATURES            "${__SERIALIZED_FEATURES}")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} LINKPARS              "${__SERIALIZED_LINKPARS}")
	_add_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_PARENTS             "${__PARENT_INSTANCE_ID}")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} IS_PROMISE            "1")
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} FEATUREBASE            "")
	_retrieve_instance_data(${__INSTANCE_ID} FEATUREBASE __TMP)
	_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} I_TEMPLATE_NAME        ${__TEMPLATE_NAME})
	_retrieve_instance_data(${__INSTANCE_ID} I_TEMPLATE_NAME __TMP)
#	message(STATUS "_store_instance_link_data(): Retrieved I_TEMPLATE_NAME: ${__TMP} for __INSTANCE_ID: ${__INSTANCE_ID}")
	if(__IS_TARGET_FIXED)
#		message(STATUS "_store_instance_link_data(): Storing fixed target name for ${__INSTANCE_ID}: ${__TEMPLATE_NAME}")
		_set_property_to_db(INSTANCEDB ${__INSTANCE_ID} TARGET_NAME  ${__TEMPLATE_NAME})
	endif()
	
#	message(STATUS "_store_instance_link_data(): __INSTANCE_ID: ${__INSTANCE_ID} __FEATUREBASE_ID: ${__FEATUREBASE_ID} __PATH_HASH: ${__PATH_HASH}")
	unset(__FOUND_TMP)
#	_retrieve_instance_data(${__INSTANCE_ID} F_INSTANCES __FOUND_TMP)
#	if(NOT "${__FOUND_TMP}" STREQUAL "")
##		message(STATUS "_store_instance_link_data(): Featurebase ${__FEATUREBASE_ID} already defined for instances ${__FOUND_TMP}. Adding another instance: ${__INSTANCE_ID} ")
#	else()
#		_add_property_to_db(GLOBAL ALL FEATUREBASES ${__FEATUREBASE_ID})
#	endif()
#	_add_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_INSTANCES           ${__INSTANCE_ID})
#	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_PATH               "${__TARGETS_CMAKE_PATH}")
#	_set_property_to_db(FEATUREBASEDB ${__FEATUREBASE_ID} F_HASH_SOURCE        "${__FEATUREBASE_HASH_SOURCE}")

	_add_property_to_db(FILEDB     ${__PATH_HASH} G_INSTANCES           ${__INSTANCE_ID})
	_set_property_to_db(FILEDB     ${__PATH_HASH} G_TEMPLATES          "${__ALL_TEMPLATE_NAMES}")

	_get_stack_depth(__STACK_DEPTH)

	if("${__STACK_DEPTH}" STREQUAL "0")
#		message(STATUS "_store_instance_link_data(): ADDING GLOBAL INSTANCE: ${__INSTANCE_ID}")
		_add_property_to_db(GLOBAL ALL INSTANCES "${__INSTANCE_ID}")
	endif()

	message(STATUS "_store_instance_link_data(): Adding __INSTANCE_ID: ${__INSTANCE_ID} for VIRTUAL_INSTANCES for ${__TEMPLATE_NAME}")
	
	_add_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} VIRTUAL_INSTANCES            ${__INSTANCE_ID})
	_set_property_to_db(TEMPLATEDB ${__TEMPLATE_NAME} T_PATH                       ${__TARGETS_CMAKE_PATH})
	
#	_retrieve_template_data(${__TEMPLATE_NAME} VIRTUAL_INSTANCES __TMP)
#	message(STATUS "_store_instance_link_data(): __INSTANCE_ID: ${__INSTANCE_ID} __TMP: ${__TMP}")
#	_retrieve_instance_data(${__INSTANCE_ID} IS_PROMISE __TMP)
#	message(STATUS "_store_instance_link_data(): __INSTANCE_ID: ${__INSTANCE_ID} IS_PROMISE: ${__TMP}")
	_debug_show_instance(${__INSTANCE_ID} 2 "   " __STR __ERROR)
	if(__ERROR)
		message(FATAL_ERROR "${ERROR}")
	endif()
	message(STATUS "_store_instance_link_data():\n ${__STR}")
endfunction()

