#Function, that takes list variable names (VAR_NAMES) and option names (OPTION_NAMES) makes a list, that can be passed as named arguments (without quotes, so it will be parsed as list).

function(prepare_arguments_to_pass )
	set(options )
	set(oneValueArgs  OUTVAR)
	set(multiValueArgs VAR_NAMES OPTION_NAMES)
	cmake_parse_arguments(__PATP "${options}" "${oneValueArgs}" "${multiValueArgs}" "${ARGN}")

	set(unparsed ${__PATP_UNPARSED_ARGUMENTS})
	if(unparsed)
		message(FATAL_ERROR "function nice_list_output: unparsed arguments: ${unparsed}")
	endif()
	set(__OUT)
	if(__PATP_VAR_NAMES)
#		message(STATUS "prepare_arguments_to_pass(): __PATP_VAR_NAMES: ${__PATP_VAR_NAMES}")
		foreach(__VAR IN LISTS __PATP_VAR_NAMES)
#			message(STATUS "prepare_arguments_to_pass(): __VAR: ${__VAR}")
			if(NOT "${${__VAR}}" STREQUAL "")
#				message(STATUS "prepare_arguments_to_pass(): __VAR: ${__VAR}: ${${__VAR}}, __OUT: ${__OUT}")
				list(APPEND __OUT ${__VAR} "${${__VAR}}")
			endif()
		endforeach()
	endif()
	if(__PATP_OPTION_NAMES)
#		message(STATUS "prepare_arguments_to_pass(): __PATP_OPTION_NAMES: ${__PATP_OPTION_NAMES}")
		foreach(__VAR IN LISTS __PATP_OPTION_NAMES)
			if(${__VAR})
#				message(STATUS "prepare_arguments_to_pass(): __VAR: ${__VAR}, __OUT: ${__OUT}")
				list(APPEND __OUT ${__VAR})
			endif()
		endforeach()
	endif()
	set(${__PATP_OUTVAR} "${__OUT}" PARENT_SCOPE)
endfunction()
